apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: scrbble
spec:
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/devnull-twitch/scrbble-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: dockerconfigjson-ghcr